# Generated by Django 5.0.6 on 2025-02-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendo', '0002_alter_customers_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=15)),
                ('to_number', models.CharField(max_length=15)),
                ('message_body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
