# Generated by Django 5.0.6 on 2025-02-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendo', '0004_chatsession_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
